# Generated by Django 3.2.9 on 2022-08-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogTitle', models.TextField(max_length=2000)),
                ('blogAuthor', models.TextField(max_length=200)),
                ('blogId', models.TextField(default=0)),
                ('blogDate', models.TextField(max_length=200)),
                ('blogContent', models.TextField(max_length=20000)),
                ('blogImage', models.TextField(max_length=2000)),
                ('blogAuthorInstaLink', models.TextField(max_length=2000)),
                ('blogAuthorFacebookLink', models.TextField(max_length=2000)),
                ('blogAuthorInfo', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='divyaProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('productHeroImage', models.ImageField(upload_to='static/assets/img')),
                ('productType', models.CharField(max_length=200)),
                ('productImage', models.ImageField(upload_to='static/assets/img')),
                ('productDescription', models.CharField(max_length=2000)),
                ('productPoints', models.CharField(max_length=2000)),
                ('productFile', models.FileField(upload_to='static/assets')),
            ],
        ),
        migrations.CreateModel(
            name='downloadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=200)),
                ('downloadFile', models.FileField(upload_to='')),
                ('modelDescription', models.TextField(max_length=4000)),
            ],
        ),
    ]
