# Generated by Django 3.2.9 on 2022-08-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyaChemicalsWebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobilenumber', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
